### ISSUE TITLE
Warning when during installation

### ISSUE THREAD

**Issue by PixelsnPolygons** [RoxanneSHS/KidoEE#1]
Hey Roxanne,

I am seeing 4 warnings during the installation of Kido for EET. Installation does complete successfully, but I am worried that weird broken things might happen if I don't address the warnings.

Here:
[PPDUEL1.DLG] loaded
WARNING: EXTEND_TOP #position 3 out of range 0-3
WARNING: EXTEND_TOP #position 3 out of range 0-2
[PLAYER1.DLG] saved	156 states, 578 trans, 16 strig, 335 ttrig, 218 actions

And here:
AMMERC01.DLG] loaded
WARNING: EXTEND_TOP #position 3 out of range 0-3
WARNING: EXTEND_BOTTOM #position 5 out of range 0-4
[HGNYA01.DLG] saved	36 states, 96 trans, 7 strig, 43 ttrig, 28 actions

[Setup-Kido.log](https://github.com/user-attachments/files/16022297/Setup-Kido.log)
[WeiDU-BGEE.log](https://github.com/user-attachments/files/16022314/WeiDU-BGEE.log)
[WeiDU.log](https://github.com/user-attachments/files/16022315/WeiDU.log)

**Comment by RoxanneSHS** [comment]
These warnings can be ignored by players, they are meant as reminders for the modder.

**Comment by PixelsnPolygons** [comment]
Thank you!

Is that generally the case with WeiDU installation warnings?

**Comment by RoxanneSHS** [comment]
Often but not always. Weidu error and warning function is not too elaborate but done by modders on case-by-case experience, it is not a product, so take what you get for free...mostly it is a modder tool, so it assumes that you know most about the function, so people just wanting to play may easily be confused by some of the output. In most cases, if the mod installs without error or stopping installation, the reports are insignificant.

**Comment by PixelsnPolygons** [comment]
I appreciate the insight. Thank you!
